// cart.js
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const SET_PRODUCTS_IN_CART = 'SET_PRODUCTS_IN_CART';

// products.js
export const SET_PRODUCT_CATEGORIES = 'SET_PRODUCT_CATEGORIES';