<table class="table table-bordered">
    <thead>
        <tr>
            <th>Amount</th>
            <th>Intesrest</th>
            <th>Rate</th>
            <th>Fee</th>
            <th>Duration</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>