<?php

// Heading
$_['heading_title'] = 'Help Categories';

// Text
$_['text_success'] = 'Success: You have modified help categories!';
$_['text_list'] = 'Help Category List';
$_['text_add'] = 'Add Help Category';
$_['text_edit'] = 'Edit Help Category';
$_['text_default'] = 'Default';

// Column
$_['column_name'] = 'Category Name';
$_['column_sort_order'] = 'Sort Order';
$_['column_action'] = 'Action';
$_['column_status'] = 'Status';
$_['column_icon'] = 'Icon';
$_['help_seo_url'] = 'Do not enter site name, just the information URL. Leave empty if you want to be generated by the system automatically based on information name.';

// Entry
$_['entry_name'] = 'Category Name';
$_['entry_icon'] = 'Category Icon';
$_['entry_column'] = 'Columns';
$_['entry_sort_order'] = 'Sort Order';
$_['entry_meta_title'] = 'Meta Tag Title';
$_['entry_meta_keyword'] = 'Meta Tag Keywords';
$_['entry_meta_description'] = 'Meta Tag Description';
$_['entry_seo_url'] = 'SEO URL';

// Error
$_['error_seo_url'] = 'SEO URL already in use!';
$_['error_warning'] = 'Warning: Please check the form carefully for errors!';
$_['error_permission'] = 'Warning: You do not have permission to modify Help categories!';
$_['error_name'] = 'Category Name must be between 2 and 32 characters!';
$_['error_icon'] = 'Icon required!';
