<?php

// Heading
$_['heading_title'] = 'Checkout Questions';

// Text
$_['text_success'] = 'Success: You have modified checkout question!';
$_['text_default'] = 'Default';
$_['text_enable'] = 'Enable';
$_['text_disable'] = 'Disable';
$_['text_list'] = 'List';

// Column
$_['column_title'] = 'Question';
$_['column_sort_order'] = 'Sort Order';
$_['column_action'] = 'Action';
$_['column_status'] = 'Status';

$_['entry_question'] = 'Question';
$_['entry_description'] = 'Description';
$_['entry_meta_title'] = 'Meta Tag Title';
$_['entry_meta_keyword'] = 'Meta Tag Keywords';
$_['entry_meta_description'] = 'Meta Tag Description';
$_['entry_seo_url'] = 'SEO URL';

// Entry
$_['entry_title'] = 'Page Title :';
$_['entry_description'] = 'Description :';
$_['entry_store'] = 'Stores :';
$_['entry_keyword'] = 'SEO Keyword :<br /><span class="help">Do not use spaces instead replace spaces with - and make sure the keyword is globally unique.</span>';
$_['entry_bottom'] = 'Bottom :<br/><span class="help">Display in the bottom footer.</span>';
$_['entry_status'] = 'Status :';
$_['entry_sort_order'] = 'Sort Order :';
$_['entry_layout'] = 'Layout Override :';
$_['tab_products'] = 'Products';
$_['entry_seo_keyword'] = 'SEO Keyword :';
$_['entry_meta_keyword'] = 'Meta Keywords :';
$_['entry_meta_desc'] = 'Meta Description :';
$_['entry_page_content'] = 'Page Content :';
$_['entry_select_products'] = 'Select products :';
$_['text_auto'] = '(Autocomplete)';

// Help
$_['help_seo_url'] = 'Do not enter site question or category, just the product URL. Leave empty if you want to be generated by the system automatically based on product question.';

// Error
$_['error_question'] = 'Question field required!';
$_['error_seo_url'] = 'SEO URL already in use!';
$_['error_warning'] = 'Warning: Please check the form carefully for errors!';
$_['error_permission'] = 'Warning: You do not have permission to modify page!';
$_['error_title'] = 'Page Title must be between 3 and 64 characters!';
$_['error_description'] = 'Description must be more than 3 characters!';
$_['error_account'] = 'Warning: This page cannot be deleted as it is currently assigned as the store account terms!';
$_['error_checkout'] = 'Warning: This page cannot be deleted as it is currently assigned as the store checkout terms!';
$_['error_affiliate'] = 'Warning: This page cannot be deleted as it is currently assigned as the store affiliate terms!';
$_['error_store'] = 'Warning: This page cannot be deleted as its currently used by %s stores!';
