name: Development Deployment
on:
  push:
    branches: [ develop ]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: dev.kwikbasket.com server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: dev.kwikbasket.com
        username: emlimadev
        key: ${{ secrets.DEV_SERVER_KEY }}
        port : 22
        script: |
          cd /var/www/html/dev.kwikbasket.com
          git pull origin develop
