name: Development Deployment
on:
  push:
    branches: [ develop ]

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: dev.kwikbasket.com server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: dev.kwikbasket.com
        username: ubuntu
        key: ${{ secrets.DEV_SERVER_KEY }}
        port : 22
        script: |
          cd /var/www/store
          git pull origin develop
