name: Development Deployment
on:
  push:
    branches: [ develop ]

jobs:
  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            ref: ${{ github.head_ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Apply php-cs-fixer changes

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: dev.kwikbasket.com server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: dev.kwikbasket.com
        username: emlimadev
        key: ${{ secrets.DEV_SERVER_KEY }}
        port : 22
        script: |
          cd /var/www/html/dev.kwikbasket.com
          git pull origin develop
